add_newline = false
prompt_order=["rust","line_break","package","line_break","character","directory"]

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
disabled = true

[[battery.display]]
threshold = 100
style = "bold red"

[character]
symbol = "â¯â¯"
error_symbol = "âœ—"
use_symbol_for_status = true

